name: Update READMEs with Paper Info

on:
  workflow_dispatch:

jobs:
  update-readmes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install PyGithub requests

      - name: Run the README update script
        env:
          GITHUB_TOKEN: ${{ secrets.ORG_SYNC_TOKEN }}
          CSV_FILENAME: VI_publications_for_Github.csv
        run: python update_readmes.py
